# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ac18b6de30a3c8103588ce1b1861515f338b4f29b939b24bad69da023548fbaf0ea9639ff49c68f2962900777d8994c1abc84cae2665503630475330d5b2c47

test:
  secret_key_base: 81d2e641dcecbed05e84add2355d300da6ed64606d962cafffeb9564eed2ed21d42d7ae2edc77bb5cb974b7c76696ebc605cbaa780e179d14bda36e8cdc019a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
